# Generated by Django 5.2.6 on 2025-09-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='city',
            field=models.CharField(default='Ikoyi', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestlog',
            name='country',
            field=models.CharField(default='Nigeria', max_length=255),
            preserve_default=False,
        ),
    ]
